HFSS-API: src/3dmodeler/hfssBox.m File Reference
hfssBox.m File Reference
Creates a box in HFSS.
Functions
noret::substitute hfssBox (matlabtypesubstitute fid, matlabtypesubstitute Name, matlabtypesubstitute Start, matlabtypesubstitute Size, matlabtypesubstitute Units, matlabtypesubstitute varargin)
Creates a box in HFSS.
Detailed Description
Creates a box in HFSS.
Definition in file hfssBox.m.
Function Documentation
noret::substitute hfssBox (matlabtypesubstitute fid, matlabtypesubstitute Name, matlabtypesubstitute Start, matlabtypesubstitute Size, matlabtypesubstitute Units, matlabtypesubstitute varargin)
Creates a box in HFSS.
Creates the VB Script necessary to create a Box (or Cuboid) in HFSS. This function also provides for optional holes (specified by their Center, Radii and Axes) in the box. This feature is useful to allow things like vias, cables etc., to penetrate the box without intersection violations.
Note
Full function call is function hfssBox(fid, Name, Start, Size, Units, [Center1], [Radius1], [Axis1], [Center2], [Radius2], [Axis2])
If you happen to specify a hole that lies outside the box, it will have no effect. The script will run without interruption.
Example
  fid = fopen('myantenna.vbs', 'wt');
 a Box with 2 holes punched thro' it.
  hfssBox(fid, 'FR4_Base', [-bpHeight/2, -baseLength/2, 0], [bpHeight, ...
          baseLength, -baseThick], 'in', [cX1, cY1, cZ1], R1, 'Z',...
          [cX2, cY2, cZ2], R2, 'X');
Parameters
fid file identifier of the HFSS script file.
Name name of the box (appears in HFSS).
Start starting location of the box (specify as [x, y, z]).
Size size of the box (specify as [sx, sy, sz]).
Units units of the box (specify using either in, mm, meter or anything else defined in HFSS).
varargin Center,Radius,Axis
Center - (Optional) center of the hole to be punched through the box. It can lie anywhere within or on the surface of the box.
Radius - (Optional) radius of the hole to be punched through the box.
Axis - (Optional) axis of the hole to be punched through the box.
Definition at line 17 of file hfssBox.m.
References hfssCylinder(), and hfssSubtract().
Referenced by hfssDipole().