HFSS-API: src/3dmodeler/hfssHollowCylinder.m File Reference
hfssHollowCylinder.m File Reference
Creates VB Script necessary to generate a hollow cylinder in HFSS.
Functions
noret::substitute hfssHollowCylinder (matlabtypesubstitute fid, matlabtypesubstitute Name, matlabtypesubstitute Axis, matlabtypesubstitute Center, matlabtypesubstitute inRadius, matlabtypesubstitute outRadius, matlabtypesubstitute Height, matlabtypesubstitute Units)
Creates VB Script necessary to generate a hollow cylinder in HFSS.
Detailed Description
Creates VB Script necessary to generate a hollow cylinder in HFSS.
Definition in file hfssHollowCylinder.m.
Function Documentation
noret::substitute hfssHollowCylinder (matlabtypesubstitute fid, matlabtypesubstitute Name, matlabtypesubstitute Axis, matlabtypesubstitute Center, matlabtypesubstitute inRadius, matlabtypesubstitute outRadius, matlabtypesubstitute Height, matlabtypesubstitute Units)
Creates VB Script necessary to generate a hollow cylinder in HFSS.
Note
This function creates an extra object that is a contatenation of the Name with _sub that gets subtracted from the outer cylinder to get the hollow structure.
Example
 fid = fopen('myantenna.vbs', 'wt');
 ...
 hfssHollowCylinder(fid, 'Dipole', 'X', [-G/2, 0, 0], 0.95*R, R, L, 'in');
Parameters
fid file identifier of the HFSS script file.
Name name of the hollow cylinder (in HFSS).
Axis choose between X, Y or Z for the cylinder axis.
Center center of the cylinder (express as [x, y, z]).
inRadius inner radius of the cylinder.
outRadius outer radius of the cylinder.
Height cylinder height.
Units units for all the quantities (use either in, mm, meter or anything else that is defined in HFSS).
Definition at line 17 of file hfssHollowCylinder.m.
References hfssCylinder(), and hfssSubtract().
Referenced by hfssCoaxialCable().