HFSS-API: src/3dmodeler/hfssUncoveredCylinder.m File Reference
hfssUncoveredCylinder.m File Reference
Functions
noret::substitute hfssUncoveredCylinder (matlabtypesubstitute fid, matlabtypesubstitute Name, matlabtypesubstitute Axis, matlabtypesubstitute Center, matlabtypesubstitute Radius, matlabtypesubstitute Height, matlabtypesubstitute Units)
Function Documentation
noret::substitute hfssUncoveredCylinder (matlabtypesubstitute fid, matlabtypesubstitute Name, matlabtypesubstitute Axis, matlabtypesubstitute Center, matlabtypesubstitute Radius, matlabtypesubstitute Height, matlabtypesubstitute Units)
Definition at line 17 of file hfssUncoveredCylinder.m.
References hfssCircle(), hfssConnect(), and hfssRename().